/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_flattree_free: (a: number, b: number) => void;
export const __wbg_wasmsparsematrix_free: (a: number, b: number) => void;
export const build_rp_tree: (a: number, b: number, c: number, d: number, e: number, f: bigint) => number;
export const cosine: (a: number, b: number, c: number, d: number) => number;
export const euclidean: (a: number, b: number, c: number, d: number) => number;
export const flattree_children: (a: number) => [number, number];
export const flattree_dim: (a: number) => number;
export const flattree_hyperplanes: (a: number) => any;
export const flattree_indices: (a: number) => [number, number];
export const flattree_n_nodes: (a: number) => number;
export const flattree_offsets: (a: number) => any;
export const search_flat_tree: (a: number, b: number, c: number, d: bigint) => [number, number];
export const sparse_add: (a: number, b: number) => number;
export const sparse_eliminate_zeros: (a: number) => number;
export const sparse_get_csr: (a: number) => any;
export const sparse_identity: (a: number) => number;
export const sparse_maximum: (a: number, b: number) => number;
export const sparse_multiply_scalar: (a: number, b: number) => number;
export const sparse_normalize: (a: number, b: number, c: number) => number;
export const sparse_pairwise_multiply: (a: number, b: number) => number;
export const sparse_subtract: (a: number, b: number) => number;
export const sparse_transpose: (a: number) => number;
export const version: () => [number, number];
export const wasmsparsematrix_get: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmsparsematrix_get_all_ordered: (a: number) => [number, number];
export const wasmsparsematrix_get_cols: (a: number) => any;
export const wasmsparsematrix_get_dims: (a: number) => [number, number];
export const wasmsparsematrix_get_rows: (a: number) => any;
export const wasmsparsematrix_get_values: (a: number) => any;
export const wasmsparsematrix_map_scalar: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmsparsematrix_n_cols: (a: number) => number;
export const wasmsparsematrix_n_rows: (a: number) => number;
export const wasmsparsematrix_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const wasmsparsematrix_nnz: (a: number) => number;
export const wasmsparsematrix_set: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmsparsematrix_to_array: (a: number) => any;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
